/**
 * Generated by scripts/eac-vault-mint.mjs — do not edit by hand.
 * Seal material for the co-paid lane: two masked shards plus the GCM payload.
 * Readable form exists nowhere; see src/vault.js for the gate and the derivation.
 */

export const LANE_SHARDS = [
  {
    "s": "ZNOAoI0gQDLQJ7iI9T8BCiD7HI1WDeep",
    "w": "7SwffsKLymPWeg9LskEIfw=="
  },
  {
    "s": "GdDFDPMbIpZAB0PxlqjLiqyal/znPi5C",
    "w": "1uMy322DuCNectE+zVAAcw=="
  }
]
export const LANE_SEAL = "K6ir4hSvjDLKLQBlGC8GBGiPKOlbqabhYDHNG+GZQQG6iUoRuLXH7F7fRAzvULNIPT8Kzpn3aQwTcNt4SsoPqxqb5bFujLRo0YM5CYZx/VymLHTh9s9t5d8DnN8Tp4kBkNEA0HCv5MgiS9xfiQm77FrQKKarCpxNRAKnRthyz4McS5UhxcEJ+SqlJB4UcE5ljXaXbqix"
