/**
 * Generated by scripts/eac-vault-mint.mjs — do not edit by hand.
 * Anchor shard for the co-paid lane seal (its peers live in vault-data.js).
 */

export const LANE_ANCHOR = {
  "s": "ivi0Yd+KNFs671wb1QsMmU16uRo26005",
  "w": "SXLUjrr2xEdsPY2v+2Ef3Q=="
}
